spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices-blog-comment
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver # Specify the driver class name
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

